//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL_MVC.ServiceReferenceSemestre {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSemestre.ISemestre")]
    public interface ISemestre {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISemestre/Add", ReplyAction="http://tempuri.org/ISemestre/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Semestre))]
        ML.Result Add(ML.Semestre semestre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISemestre/Add", ReplyAction="http://tempuri.org/ISemestre/AddResponse")]
        System.Threading.Tasks.Task<ML.Result> AddAsync(ML.Semestre semestre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISemestreChannel : PL_MVC.ServiceReferenceSemestre.ISemestre, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SemestreClient : System.ServiceModel.ClientBase<PL_MVC.ServiceReferenceSemestre.ISemestre>, PL_MVC.ServiceReferenceSemestre.ISemestre {
        
        public SemestreClient() {
        }
        
        public SemestreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SemestreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SemestreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SemestreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ML.Result Add(ML.Semestre semestre) {
            return base.Channel.Add(semestre);
        }
        
        public System.Threading.Tasks.Task<ML.Result> AddAsync(ML.Semestre semestre) {
            return base.Channel.AddAsync(semestre);
        }
    }
}
